# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: config-init-load
resources:
  - jobs.yaml
  - roles.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: gluufederation/config-init
    newTag: 4.1.0_01
configMapGenerator:
  - name: config-cm
    literals:
      - GLUU_CONFIG_KUBERNETES_NAMESPACE="default"
      - GLUU_SECRET_KUBERNETES_NAMESPACE="default"
      - GLUU_CONFIG_ADAPTER="kubernetes"
      - GLUU_SECRET_ADAPTER="kubernetes"
      - GLUU_CACHE_TYPE=GLUUCACHETYPE
  - name: config-generate-params
    files:
      - generate.json
