# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "persistence.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  GLUU_OXTRUST_API_ENABLED: {{ .Values.configmap.gluuOxtrustApiEnabled | quote }}
  GLUU_OXTRUST_API_TEST_MODE: {{ .Values.configmap.gluuOxtrustApiTestMode | quote }}
  GLUU_CONFIG_KUBERNETES_NAMESPACE: {{ .Release.Namespace | quote }}
  GLUU_SECRET_KUBERNETES_NAMESPACE: {{ .Release.Namespace | quote }}
  GLUU_DOCUMENT_STORE_TYPE: {{ .Values.global.gluuDocumentStoreType | quote }}
  GLUU_JCA_RMI_URL: {{ .Values.global.gluuJcaRmiUrl | quote }}
  GLUU_JCA_USERNAME: {{ .Values.global.gluuJcaUsername | quote }}
  GLUU_JCA_PASSWORD_FILE: {{ .Values.global.gluuJcaPasswordFile | quote }}
  # Auto enable installation of some services
  GLUU_CASA_ENABLED: {{ .Values.configmap.gluuCasaEnabled | quote }}
  GLUU_PASSPORT_ENABLED: {{ .Values.configmap.gluuPassportEnabled | quote }}
  GLUU_RADIUS_ENABLED: {{ .Values.configmap.gluuRadiusEnabled | quote }}
  {{- if .Values.global.oxshibboleth.enabled }}
  GLUU_SAML_ENABLED: {{ .Values.configmap.gluuSamlEnabled | quote }}
  {{- end }}

  GLUU_CONFIG_ADAPTER: {{ .Values.global.configAdapterName | quote }}
  GLUU_SECRET_ADAPTER: {{ .Values.global.configSecretAdapter | quote }}
  GLUU_CACHE_TYPE: {{ .Values.global.gluuCacheType | quote }}
  GLUU_PERSISTENCE_TYPE: {{ .Values.global.gluuPersistenceType | quote }}
  {{ if eq .Values.global.gluuCacheType "REDIS" }}
  GLUU_REDIS_URL: {{ .Values.global.gluuRedisUrl | quote }}
  GLUU_REDIS_TYPE: {{ .Values.global.gluuRedisType | quote }}
  GLUU_REDIS_USE_SSL: {{ .Values.global.gluuRedisUseSsl | quote }}
  GLUU_REDIS_SSL_TRUSTSTORE: {{ .Values.global.gluuRedisSslTruststore | quote }}
  GLUU_REDIS_SENTINEL_GROUP: {{ .Values.global.gluuRedisSentinelGroup | quote }}
  {{- end }}
  # options: default/user/site/cache/statistic used only if GLUU_PERSISTENCE_TYPE is hybrid
  {{- if or (eq .Values.global.gluuPersistenceType "hybrid") (eq .Values.global.gluuPersistenceType "ldap") }}
  GLUU_PERSISTENCE_LDAP_MAPPING: {{ .Values.global.gluuPersistenceLdapMapping | quote }}
  {{- end }}
  {{- if or (eq .Values.global.gluuPersistenceType "ldap") (eq .Values.global.gluuPersistenceType "hybrid")  }}
  # used only if GLUU_PERSISTENCE_TYPE is ldap or hybrid
  GLUU_LDAP_URL: {{ .Values.global.gluuLdapUrl | quote }}
  {{- else if or (eq .Values.global.gluuPersistenceType "couchbase") (eq .Values.global.gluuPersistenceType "hybrid") }}
  #  used only if GLUU_PERSISTENCE_TYPE is couchbase or hybrid
  GLUU_COUCHBASE_URL: {{ .Values.global.gluuCouchbaseUrl }}
  GLUU_COUCHBASE_USER: {{ .Values.global.gluuCouchbaseUser }}
  GLUU_COUCHBASE_CERT_FILE: {{ .Values.global.gluuCouchbaseCertFile | quote }}
  GLUU_COUCHBASE_PASSWORD_FILE: {{ .Values.global.gluuCouchbasePassFile | quote }}
  {{- end }}
