apiVersion: v1
data:
  DOMAIN: demoexample.gluu.org #<-- Change this to your FQDN
  GLUU_CACHE_TYPE: NATIVE_PERSISTENCE #<-- Change this if necessary
  GLUU_CONFIG_ADAPTER: kubernetes
  GLUU_CONFIG_KUBERNETES_NAMESPACE: gluu  #<-- Change this to Gluus namespace
  GLUU_LDAP_URL: opendj:1636
  GLUU_PERSISTENCE_TYPE: ldap
  GLUU_SECRET_ADAPTER: kubernetes
  GLUU_SECRET_KUBERNETES_NAMESPACE: gluu #<-- Change this to Gluus namespace
kind: ConfigMap
metadata:
  labels:
    app: gluu-upgrade
  name: upgrade-cm
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: gluu-upgrade
  name: gluu-upgrade-job
spec:
  template:
    metadata:
      labels:
        app: gluu-upgrade
    spec:
      containers:
      - args:
        - --source
        - "4.1"
        - --target
        - "4.2"
        envFrom:
        - configMapRef:
            name: upgrade-cm
        image: gluufederation/upgrade:4.2.1_02
        name: gluu-upgrade-job
      restartPolicy: Never
