# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jackrabbit.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  GLUU_CONFIG_KUBERNETES_NAMESPACE: {{ .Release.Namespace | quote }}
  GLUU_CONFIG_ADAPTER: {{ .Values.global.configAdapterName | quote }}
