# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "gluu-gateway-ui.fullname" . }}-preperation
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
        {{- range .Values.nginxIngress.tls }}
        - name: tls-certificate
          secret:
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
            secretName: {{ .secretName }}
        {{- end }}
      containers:
        - name: {{ include "gluu-gateway-ui.fullname" . }}-preperation
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "gluu-gateway-ui.fullname" . }}-postgres-pass
                  key: DB_PASSWORD
          envFrom:
          - configMapRef:
              name: {{ template "gluu-gateway-ui.fullname" . }}-cm
          volumeMounts:
            - mountPath: /etc/certs
              name: tls-certificate
          command:
            - /bin/sh
            - -c
            - |
                ./entrypoint.sh -c prepare -a postgres -u postgresql://konga:konga@postgres.postgres.svc.cluster.local:5432/konga