# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: persistence-load
resources:
  - jobs.yaml
images:
  - name: gluufederation/persistence
    newTag: 4.1.0_01
configMapGenerator:
  - name: persistence-cm
    literals:
      - GLUU_CONFIG_KUBERNETES_NAMESPACE="default"
      - GLUU_SECRET_KUBERNETES_NAMESPACE="default"
      - GLUU_CONFIG_ADAPTER="kubernetes"
      - GLUU_SECRET_ADAPTER="kubernetes"
      - GLUU_DOCUMENT_STORE_TYPE="JCA"
      - GLUU_JCA_RMI_URL="http://jackrabbit:8080/rmi"
      - GLUU_JCA_USERNAME="admin"
      - GLUU_JCA_PASSWORD_FILE="/etc/gluu/conf/jca_password"
      - DOMAIN=FQDN
      # options: ldap/couchbase/hybrid
      - GLUU_PERSISTENCE_TYPE=PERSISTENCETYPE
      # options: default/user/site/cache/statistic; used only if GLUU_PERSISTENCE_TYPE is hybrid
      - GLUU_PERSISTENCE_LDAP_MAPPING=LDAPMAPPING
      # used only if GLUU_PERSISTENCE_TYPE is ldap or hybrid
      - GLUU_LDAP_URL="opendj:1636"
      # used only if GLUU_PERSISTENCE_TYPE is couchbase or hybrid
      - GLUU_COUCHBASE_URL=COUCHBASEURL
      - GLUU_COUCHBASE_USER=CBUSER
      - GLUU_COUCHBASE_CERT_FILE="/etc/certs/couchbase.crt"
      - GLUU_COUCHBASE_PASSWORD_FILE="/etc/gluu/conf/couchbase_password"
      - GLUU_CACHE_TYPE=GLUUCACHETYPE
      - GLUU_OXTRUST_API_ENABLED=GLUUOXTRUSTAPIENABLED
      - GLUU_OXTRUST_API_TEST_MODE=GLUUOXTRUSTAPITESTMODE
      - GLUU_CASA_ENABLED=GLUUCASAENABBLED
      - GLUU_PASSPORT_ENABLED=GLUUPASSPORTENABLED
      - GLUU_RADIUS_ENABLED=GLUURADIUSENABLED
      - GLUU_SAML_ENABLED=GLUUSAMLENABLED
