# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: radius
resources:
  - deployments.yaml
  - services.yaml
images:
  - name: gluufederation/radius
    newTag: 4.1.0_01
configMapGenerator:
  - name: radius-cm
    literals:
      - GLUU_CONFIG_KUBERNETES_NAMESPACE="default"
      - GLUU_SECRET_KUBERNETES_NAMESPACE="default"
      - LB_ADDR=LBADDR
      - GLUU_CONFIG_ADAPTER="kubernetes"
      - GLUU_SECRET_ADAPTER="kubernetes"
      - DOMAIN=FQDN
      # used only if GLUU_PERSISTENCE_TYPE is ldap or hybrid
      -  GLUU_MAX_RAM_PERCENTAGE="75.0"
      - GLUU_OXAUTH_BACKEND="oxauth:8080"
      #-  GLUU_MAX_RAM_PERCENTAGE="75.0"
      # options: ldap/couchbase/hybrid
      - GLUU_PERSISTENCE_TYPE=PERSISTENCETYPE
      # options: default/user/site/cache/statistic; used only if GLUU_PERSISTENCE_TYPE is hybrid
      - GLUU_PERSISTENCE_LDAP_MAPPING=LDAPMAPPING
      # used only if GLUU_PERSISTENCE_TYPE is ldap or hybrid
      - GLUU_LDAP_URL="opendj:1636"
      # used only if GLUU_PERSISTENCE_TYPE is couchbase or hybrid
      - GLUU_COUCHBASE_URL=COUCHBASEURL
      - GLUU_COUCHBASE_USER=CBUSER
      - GLUU_COUCHBASE_CERT_FILE="/etc/certs/couchbase.crt"
      - GLUU_COUCHBASE_PASSWORD_FILE="/etc/gluu/conf/couchbase_password"