# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v1
kind: Service
metadata:
  name: radius
  labels:
    app: radius
spec:
  ports:
  - port: 1812
    name: radius-authentication
  - port: 1813
    name: radius-accounting
  - port: 8080
    name: jetty-service
  selector:
    app: radius