apiVersion: couchbase.com/v1
kind: CouchbaseCluster
metadata:
  name: CLUSTERNAME #DO NOT CHANGE THIS LINE
spec:
  baseImage: couchbase/server
  version: enterprise-6.5.0
  antiAffinity: false
  tls:
    static:
      member:
        serverSecret: couchbase-server-tls
      operatorSecret: couchbase-operator-tls
  authSecret: cb-auth
  exposeAdminConsole: true
  adminConsoleServices:
    - data
  exposedFeatures:
    - xdcr
    - client
  exposedFeatureServiceType: NodePort
  cluster:
    dataServiceMemoryQuota: 4024
    indexServiceMemoryQuota: 1024
    searchServiceMemoryQuota: 1024
    eventingServiceMemoryQuota: 1024
    analyticsServiceMemoryQuota: 1024
    indexStorageSetting: memory_optimized
    autoFailoverTimeout: 10
    autoFailoverMaxCount: 3
    autoFailoverOnDataDiskIssues: true
    autoFailoverOnDataDiskIssuesTimePeriod: 120
    autoFailoverServerGroup: false
  buckets:
    - name: gluu #DO NOT CHANGE THIS LINE
      type: couchbase
      memoryQuota: 800
      replicas: 1
      ioPriority: high
      evictionPolicy: valueOnly
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
      compressionMode: passive
    - name: gluu_cache #DO NOT CHANGE THIS LINE
      type: couchbase
      memoryQuota: 800
      replicas: 1
      ioPriority: high
      evictionPolicy: valueOnly
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
      compressionMode: passive
    - name: gluu_site #DO NOT CHANGE THIS LINE
      type: couchbase
      memoryQuota: 800
      replicas: 1
      ioPriority: high
      evictionPolicy: valueOnly
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
      compressionMode: passive
    - name: gluu_token #DO NOT CHANGE THIS LINE
      type: couchbase
      memoryQuota: 800
      replicas: 1
      ioPriority: high
      evictionPolicy: valueOnly
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
      compressionMode: passive
    - name: gluu_user #DO NOT CHANGE THIS LINE
      type: couchbase
      memoryQuota: 800
      replicas: 1
      ioPriority: high
      evictionPolicy: valueOnly
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
      compressionMode: passive

  servers:
    - name: analytics-us-west-2a
      size: 1
      services:
        - search
        - analytics
        - eventing
      serverGroups:
       - us-west-2a
      pod:
        volumeMounts:
          default: pvc-general  
          analytics: 
            - pvc-analytics     
    - name: analytics-us-west-2b
      size: 1
      services:
        - search
        - analytics
        - eventing
      serverGroups:
       - us-west-2b
      pod:
        volumeMounts:
          default: pvc-general
          analytics: 
            - pvc-analytics 
    - name: data-us-west-2c
      size: 1
      services:
        - data
      serverGroups:
       - us-west-2c
      pod:
        volumeMounts:
          default: pvc-general  
          data: pvc-data     
    - name: data-us-west-2b
      size: 1
      services:
        - data
      serverGroups:
       - us-west-2b
      pod:
        volumeMounts:
          default: pvc-general 
          data: pvc-data     
    - name: index-us-west-2a
      size: 1
      services:
        - query
        - index
      serverGroups:
       - us-west-2a
      pod:
        volumeMounts:
          default: pvc-general
          index: pvc-index
    - name: index-us-west-2c
      size: 1
      services:
        - query
        - index
      serverGroups:
       - us-west-2c
      pod:
        volumeMounts:
          default: pvc-general
          index: pvc-index
    - name: query-us-west-2a
      size: 1
      services:
        - query
      serverGroups:
       - us-west-2a
      pod:
        volumeMounts:
          default: pvc-general
          query: pvc-query
    - name: query-us-west-2c
      size: 1
      services:
        - query
      serverGroups:
       - us-west-2c
      pod:
        volumeMounts:
          default: pvc-general
          query: pvc-query
  securityContext:
    fsGroup: 1000
  volumeClaimTemplates:
    - metadata:
        name: pvc-general
      spec:
        storageClassName: couchbase-sc
        resources:
          requests:
            storage: 20Gi
    - metadata:
        name: pvc-data
      spec:
        storageClassName: couchbase-sc
        resources:
          requests:
            storage: 100Gi
    - metadata:
        name: pvc-index
      spec:
        storageClassName: couchbase-sc
        resources:
          requests:
            storage: 60Gi
    - metadata:
        name: pvc-query
      spec:
        storageClassName: couchbase-sc
        resources:
          requests:
            storage: 60Gi
    - metadata:
        name: pvc-analytics
      spec:
        storageClassName: couchbase-sc
        resources:
          requests:
            storage: 20Gi