apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: postgres
spec:
  version: "11.1"
  init:
    scriptSource:
      secret:
        secretName: pg-init-sql
  monitor:
    agent: prometheus.io/coreos-operator
    prometheus:
      interval: 10s
      labels:
        app: postgres
      namespace: postgres
  podTemplate:
    spec:
      resources:
        limits:
          cpu: 500m
          memory: 128Mi
        requests:
          cpu: 250m
          memory: 64Mi
  replicas: "3"
  standbyMode: Hot
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 4Gi
    storageClassName: postgres-sc
  storageType: Durable
  terminationPolicy: WipeOut
  updateStrategy:
    type: RollingUpdate