{{ if eq .Values.global.gluuJackrabbitCluster "true" }}
# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v1
kind: Secret
metadata:
    name: gluu-jackrabbit-admin-pass
    namespace: {{ .Release.Namespace }}
data:
    jackrabbit_admin_password: {{ .Values.secrets.gluuJackrabbitAdminPass | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
    name: gluu-jackrabbit-postgres-pass
    namespace: {{ .Release.Namespace }}
data:
    postgres_password: {{ .Values.secrets.gluuJackrabbitPostgresPass | b64enc }}
{{- end -}}
