# License terms and conditions for Gluu Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "jackrabbit.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    storage: jackrabbit
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
    {{- if eq .Values.global.provisioner "openebs.io/local" }}
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: hostpath
      - name: BasePath
        value: /var/local-hostpath
    {{- end }}
provisioner: {{ .Values.global.provisioner }}
parameters:
  {{- if eq .Values.global.provisioner "kubernetes.io/aws-ebs" }}
  type: gp2
  fsType: {{ .Values.global.fsType }}
  {{- else if eq .Values.global.provisioner "kubernetes.io/gce-pd" }}
  type: {{ .Values.global.gcePdStorageType }}
  {{- else if eq .Values.global.provisioner "kubernetes.io/azure-disk" }}
  storageAccountType: {{ .Values.global.azureStorageAccountType }}
  kind: {{ .Values.global.azureStorageKind }}
  {{- else if eq .Values.global.provisioner "dobs.csi.digitalocean.com" }}
  {{- else if eq .Values.global.provisioner "openebs.io/local" }}
  {{- else }}
  pool: {{ .Values.global.pool }}
  fsType: {{ .Values.global.fsType }}
  {{- end }}
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: {{ .Values.global.reclaimPolicy }}
mountOptions:
  - debug
