apiVersion: v1
data:
  redis.conf: |
    cluster-enabled yes
    cluster-config-file /data/nodes.conf
    cluster-node-timeout 5000
    cluster-migration-barrier 1
    dir /data
    appendonly yes
    protected-mode no
kind: ConfigMap
metadata:
  name: redis-cluster-configmap